"use client";

import { useState } from "react";
import type { Recommendation } from "@/app/api/analyze/route";

interface PunchListProps {
  recommendations: Recommendation[];
  overallScore: number;
  overallHeadline: string;
}

const difficultyConfig = {
  easy: {
    label: "Easy win",
    badge: "bg-emerald-50 border-emerald-200 text-emerald-700 dark:bg-emerald-400/10 dark:border-emerald-400/20 dark:text-emerald-400",
    dot: "bg-emerald-500 dark:bg-emerald-400",
  },
  moderate: {
    label: "Some effort",
    badge: "bg-amber-50 border-amber-200 text-amber-700 dark:bg-amber-400/10 dark:border-amber-400/20 dark:text-amber-400",
    dot: "bg-amber-500 dark:bg-amber-400",
  },
  significant: {
    label: "Significant redesign",
    badge: "bg-rose-50 border-rose-200 text-rose-700 dark:bg-rose-400/10 dark:border-rose-400/20 dark:text-rose-400",
    dot: "bg-rose-500 dark:bg-rose-400",
  },
};

const dimensionLabels: Record<string, string> = {
  context_specificity: "Context Specificity",
  task_openness: "Task Openness",
  process_visibility: "Process Visibility",
  output_type: "Output Type",
  verification_surface: "Verification Surface",
};

export default function PunchList({ recommendations, overallScore, overallHeadline }: PunchListProps) {
  const [copied, setCopied] = useState(false);

  function buildCopyText() {
    const date = new Date().toLocaleDateString("en-US", {
      month: "long", day: "numeric", year: "numeric",
    });

    const grouped = {
      easy: recommendations.filter((r) => r.difficulty === "easy"),
      moderate: recommendations.filter((r) => r.difficulty === "moderate"),
      significant: recommendations.filter((r) => r.difficulty === "significant"),
    };

    const lines: string[] = [
      "FIRST LIGHT — ASSESSMENT ANALYSIS",
      date,
      "",
      `Overall score: ${overallScore.toFixed(1)}/10`,
      overallHeadline,
      "",
      "RECOMMENDED IMPROVEMENTS",
      "=".repeat(48),
      "",
    ];

    const sections: [string, typeof grouped.easy][] = [
      ["EASY WINS — no structural changes required", grouped.easy],
      ["SOME EFFORT — requires redesign", grouped.moderate],
      ["SIGNIFICANT REDESIGN — rethink from scratch", grouped.significant],
    ];

    for (const [header, items] of sections) {
      if (items.length === 0) continue;
      lines.push(header);
      lines.push("-".repeat(48));
      for (const r of items) {
        lines.push(`☐  [${dimensionLabels[r.dimension] || r.dimension}] ${r.title}`);
        lines.push(`   ${r.action}`);
        lines.push("");
      }
    }

    lines.push("—");
    lines.push("Generated by First Light · For educational use");
    return lines.join("\n");
  }

  function handleCopy() {
    navigator.clipboard.writeText(buildCopyText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="mt-10">
      <div className="flex items-start justify-between mb-4 gap-4">
        <div>
          <h2 className="text-xs font-semibold text-neutral-400 dark:text-white/30 tracking-widest uppercase">
            Punch List
          </h2>
          <p className="text-xs text-neutral-500 dark:text-white/30 mt-0.5 leading-relaxed">
            Specific changes that reduce AI susceptibility — copy to share with a teaching center or paste into your own notes.
          </p>
        </div>
        <button
          onClick={handleCopy}
          className="flex-shrink-0 flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-neutral-200 dark:border-white/10 text-neutral-500 dark:text-white/40 hover:text-neutral-800 dark:hover:text-white/70 hover:border-neutral-300 dark:hover:border-white/20 bg-white dark:bg-white/[0.02] transition-colors"
        >
          {copied ? (
            <>
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                <path d="M2 6l3 3 5-5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Copied
            </>
          ) : (
            <>
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                <rect x="4" y="4" width="7" height="7" rx="1" stroke="currentColor" strokeWidth="1.2" />
                <path d="M8 4V2a1 1 0 00-1-1H2a1 1 0 00-1 1v5a1 1 0 001 1h2" stroke="currentColor" strokeWidth="1.2" />
              </svg>
              Copy for doc or email
            </>
          )}
        </button>
      </div>

      <div className="space-y-2.5">
        {recommendations.map((rec, i) => {
          const cfg = difficultyConfig[rec.difficulty];
          return (
            <div
              key={i}
              className="rounded-xl border border-neutral-200 dark:border-white/8 bg-white dark:bg-white/[0.02] p-4"
            >
              <div className="flex items-start gap-3">
                <span className={`w-2 h-2 rounded-full flex-shrink-0 mt-1.5 ${cfg.dot}`} />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap mb-1.5">
                    <span className="text-xs font-mono text-neutral-400 dark:text-white/30">
                      {dimensionLabels[rec.dimension] || rec.dimension}
                    </span>
                    <span className={`text-xs font-semibold px-2 py-0.5 rounded-full border ${cfg.badge}`}>
                      {cfg.label}
                    </span>
                  </div>
                  <p className="text-sm font-semibold text-neutral-800 dark:text-white/80 mb-1.5 leading-snug">
                    {rec.title}
                  </p>
                  <p className="text-xs text-neutral-500 dark:text-white/45 leading-relaxed">
                    {rec.action}
                  </p>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
